---
- name: setup tomcat
  hosts: all
  become: true
  tasks:
  - name:  install java on RedHat
    yum:
      name: java
      state: installed
    when: ansible_os_family == "RedHat"


  - name:  install java on Debian
    apt:
      name: default-jdk
      state: present
    when: ansible_os_family == "Debian"

  - name: download tomcat
    get_url:
     url: https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.56/bin/apache-tomcat-9.0.56.tar.gz
     dest: /opt
    
  - name: extract tomact file
    unarchive:
      src: /opt/apache-tomcat-9.0.56.tar.gz
      dest: /opt
      remote_src: True

  - name: providing execute permissions
    file:
     path: /opt/apache-tomcat-9.0.56/bin/startup.sh
     mode: 0777

  - name: start tomcat service
    shell: nohup ./startup.sh
    args:
      chdir: /opt/apache-tomcat-9.0.56/bin

      



